- name: cdl_content
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
    - nembery.skillet

  tasks:
    # currently using clear text vars for testing
    - name: grab auth creds
      include_vars: 'vars.yml'
      no_log: 'yes'

    # this is a greenfield playbook adding a new cert so delete existing cert if exists
    - name: delete cdl certificate
      panos_op:
        provider: '{{ provider }}'
        cmd: 'request logging-service-forwarding certificate delete'
      register: cdl_delete_response | default('')
      until: cdl_delete_response is not failed
      retries: 2
      delay: 5
      ignore_errors: True

    # debug output to show cert delete message
    - name: delete cdl cert response
      debug: msg='{{ (cdl_delete_response.stdout | from_json).response.result }}'

    # force quit to test part of playbook
    - set_fact: stop_playbook='stop'
    - name: stop playbook
      fail: msg="planned stop during testing"
      when: stop_playbook == 'stop'