- name: cdl_content
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
    - nembery.skillet

  tasks:
    # currently using clear text vars for testing
    - name: grab auth creds
      include_vars: 'vars.yml'
      no_log: 'yes'

    # read in the skillet content from a repo
    - name: download the CDL global config skillet
      git:
        repo: '{{ skillet_repo }}'
        dest: '{{ playbook_dir }}/files'
        version: '{{ branch }}'
      tags:
        - always

    # play the named skillet to configure fw elements
    - name: play cdl global config skillet
      panos_skillet:
        skillet_path: '{{ playbook_dir }}/files'
        skillet: '{{ skillet }}'
        provider: '{{ provider }}'
        vars: '{{ skillet_vars }}'
      register: skillet_output

    # output of config push
    - name: dump test output
      debug:
        msg: '{{ skillet_output }}'


    # force quit to test part of playbook
    - set_fact: stop_playbook='stop'
    - name: stop playbook
      fail: msg="planned stop during testing"
      when: stop_playbook == 'stop'