- name: cdl_content
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
    - nembery.skillet

  tasks:
    # currently using clear text vars for testing
    - name: grab auth creds
      include_vars: 'vars.yml'
      no_log: 'yes'

    # remove directory to ensure a clean load
    - name: Recursively remove directory
      file:
        path: '{{ playbook_dir }}/files/cdl_global_config_xml_snippets'
        state: absent

    # create the skillet file directory
    - name: Create skillet directory if it does not exist
      file:
        path: '{{ playbook_dir }}/files/cdl_global_config_xml_snippets'
        state: directory
        mode: '0755'

    # download and store the skillet file
    - name: Store file into files/testme
      get_url:
        url: https://raw.githubusercontent.com/PaloAltoNetworks/panos-logging-skillets/master/cdl_global_config_xml_snippets/.meta-cnc.yaml
        validate_certs: no
        dest: '{{ playbook_dir }}/files/cdl_global_config_xml_snippets/.meta-cnc.yaml'

    # play the named skillet to configure fw elements
    - name: play cdl global config skillet
      panos_skillet:
        skillet_path: '{{ playbook_dir }}/files/cdl_global_config_xml_snippets'
        skillet: '{{ skillet }}'
        provider: '{{ provider }}'
        vars: '{{ skillet_vars }}'
      register: skillet_output

    # output of config push
    - name: dump test output
      debug:
        msg: '{{ skillet_output }}'

    # option to remove and clean out directory when playbook done
    - name: remote skillet directory cdl_global_config_xml_snippets
      file:
        path: '{{ playbook_dir }}/files/cdl_global_config_xml_snippets'
        state: absent

    # force quit to test part of playbook
    - set_fact: stop_playbook='stop'
    - name: stop playbook
      fail: msg="planned stop during testing"
      when: stop_playbook == 'stop'