- name: cdl_content
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos
    - nembery.skillet

  tasks:
    # currently using clear text vars for testing
    - name: grab auth creds
      include_vars: 'vars.yml'
      no_log: 'yes'

    - name: Recursively remove directory
      file:
        path: '{{ playbook_dir }}/files/panos-logging-skillets'
        state: absent

    # read in the skillet content from a repo
    - name: download the CDL global config skillet
      git:
        repo: '{{ skillet_repo }}'
        dest: '{{ playbook_dir }}/files/panos-logging-skillets'
        version: '{{ branch }}'
      tags:
        - always

    - name: test second repo
      git:
        repo: '{{ skillet_repo2 }}'
        dest: '{{ playbook_dir }}/files/testrepo'
        version: '{{ branch }}'
      tags:
        - always

    - name: Recursively remove directory
      file:
        path: '{{ playbook_dir }}/files/panos-logging-skillets'
        state: absent

    # force quit to test part of playbook
    - set_fact: stop_playbook='stop'
    - name: stop playbook
      fail: msg="planned stop during testing"
      when: stop_playbook == 'stop'