name: add_cdl_and_eal_to_logging_profile
label: Add Cortex Data Lake with Enhanced App Logging to Log Forwarding Profile
description: |
  Find named log forwarding profile in the configuration and update all
  log types with CDL and enabled EAL logging
type: panos
labels:
  collection: Unknown
variables:

  - name: log_profile_name
    description: name of logging profile to update
    default: default
    type_hint: text

snippets:

- name: device_config_file
  cmd: parse
  variable: config
  outputs:
    - name: shared_log_profile
      capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ntp-servers